spring:
  application:
    name: subscriptions
  datasource:
    url: jdbc:postgresql://localhost:5432/subscriptions_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    enabled: true
  packages-to-scan: com.spec.subscriptions.controller.controller, com.spec.subscriptions.controller.openapi
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

